### PR TITLE
Add Single Assignment C (SaC) compiler

### PR DESCRIPTION
**Pull request by hv15**
Hi, I'd like to add support for the Single-Assignment C (SaC) compiler (https://sac-home.org/) to glot.io. I've extended `language.rs`, and have tested it locally. I'm currently also adding SaC support to https://github.com/glotcode/glot-images (https://github.com/glotcode/glot-images/pull/3).

### CODE REVIEW

**Comment by hv15** [comment]
I tried running sac2c within the built image from glot-images, and it seems that there is no `/tmp` path in the image. Sac2c uses this to store intermediary files before generating the binary. I'm working on a solution around this.

**Comment by prasmussen** [comment]
> I tried running sac2c within the built image from glot-images, and it seems that there is no `/tmp` path in the image. Sac2c uses this to store intermediary files before generating the binary. I'm working on a solution around this.

Are you using one of the existing images or are you creating a new?
On glot.io I'm mounting a tmpfs dir on /tmp so it should be available, if you are running them directly via docker you might need to use the flag `--tmpfs /tmp` or something like that.

I'm not familiar with SaC but will gladly merge it if you are able to create the image for it.
Note that I'm using [nix](https://nixos.org/) to build the container images and if the SaC compiler is not available as a nix package it might be a big learning curve to add it (depending on you nix experience, etc).

**Comment by hv15** [comment]
Yes, we have a nix package at https://github.com/cxandru/sac-nix... its a flake, but I've gotten it to load/setup/install the sac stuff into the glot image.

Ahhh that was it, thanks for `--tmpfs /tmp`. Yes I locally created an image for the sac code runner, with that extra flag it works as expected!

The PR is ready to merge :smile_cat:

**Comment by prasmussen** [comment]
Awesome!

**Pull request merged**
